config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/models/neighbors_invitation.rb
class NeighborsInvitation < ActiveRecord::Base
  module Statuses
  	NEW = 'new'
  	ACCEPTED = 'accepted'
  	CANCELED = 'canceled'
    REJECTED = 'rejected'
  end
  belongs_to :family
  belongs_to :invited_family, class_name: 'Family'
  belongs_to :user
  belongs_to :respond_by, class_name: 'User'
  has_many :neighbors_families_links

  validates :invitation_text, presence: true
  validates :invited_at, presence: true

  after_save :update_neighbors_families_links
  after_create :send_neighbors_invitation_messages

  scope :pending, -> {where(status: Statuses::NEW)}
  scope :rejected, -> {where(status: Statuses::REJECTED)}
  scope :accepted, -> {where(status: Statuses::ACCEPTED)}
  scope :cancelled, -> {where(status: Statuses::CANCELED)}

  def accepted?
  	status == Statuses::ACCEPTED
  end

  def update_neighbors_families_links
    neighbors_families_links.destroy
    if accepted?
      neighbors_families_links.create!(family: family, neighbor_family: invited_family, initiator: true)
      neighbors_families_links.create!(family: invited_family, neighbor_family: family, initiator: false)
    end
  end

  def send_neighbors_invitation_messages
    sender_app = user.app
    family.supervisors.each do |supervisor|
      Info.create_initiated_neighbors_invitation_message(self, supervisor)
    end
    invited_family.parents.each do |parent|
      Info.create_invited_neighbors_invitation_message(self, parent)
    end
  end
end

app/controllers/api/v1/neighbors_invitations_controller.rb
class NeighborsInvitationsController < ApplicationController
  before_action :set_neighbors_invitation, only: [:show, :edit, :update, :destroy]

  # GET /neighbors_invitations
  # GET /neighbors_invitations.json
  def index
    @neighbors_invitations = NeighborsInvitation.all
  end

  # GET /neighbors_invitations/1
  # GET /neighbors_invitations/1.json
  def show
  end

  # GET /neighbors_invitations/new
  def new
    @neighbors_invitation = NeighborsInvitation.new
  end

  # GET /neighbors_invitations/1/edit
  def edit
  end

  # POST /neighbors_invitations
  # POST /neighbors_invitations.json
  def create
    @neighbors_invitation = NeighborsInvitation.new(neighbors_invitation_params)

    respond_to do |format|
      if @neighbors_invitation.save
        format.html { redirect_to @neighbors_invitation, notice: 'Neighbors invitation was successfully created.' }
        format.json { render :show, status: :created, location: @neighbors_invitation }
      else
        format.html { render :new }
        format.json { render json: @neighbors_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighbors_invitations/1
  # PATCH/PUT /neighbors_invitations/1.json
  def update
    respond_to do |format|
      if @neighbors_invitation.update(neighbors_invitation_params)
        format.html { redirect_to @neighbors_invitation, notice: 'Neighbors invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighbors_invitation }
      else
        format.html { render :edit }
        format.json { render json: @neighbors_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighbors_invitations/1
  # DELETE /neighbors_invitations/1.json
  def destroy
    @neighbors_invitation.destroy
    respond_to do |format|
      format.html { redirect_to neighbors_invitations_url, notice: 'Neighbors invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighbors_invitation
      @neighbors_invitation = NeighborsInvitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighbors_invitation_params
      params.require(:neighbors_invitation).permit(:family_id, :neighbor_id, :status, :user_id, :initial_text, :respond_by_id, :response_text, :respond_at)
    end
end

app/controllers/neighbors_invitations_controller.rb
class NeighborsInvitationsController < ApplicationController
  before_action :set_neighbors_invitation, only: [:show, :edit, :update, :destroy]

  # GET /neighbors_invitations
  # GET /neighbors_invitations.json
  def index
    @neighbors_invitations = NeighborsInvitation.all
  end

  # GET /neighbors_invitations/1
  # GET /neighbors_invitations/1.json
  def show
  end

  # GET /neighbors_invitations/new
  def new
    @neighbors_invitation = NeighborsInvitation.new
  end

  # GET /neighbors_invitations/1/edit
  def edit
  end

  # POST /neighbors_invitations
  # POST /neighbors_invitations.json
  def create
    @neighbors_invitation = NeighborsInvitation.new(neighbors_invitation_params)

    respond_to do |format|
      if @neighbors_invitation.save
        format.html { redirect_to @neighbors_invitation, notice: 'Neighbors invitation was successfully created.' }
        format.json { render :show, status: :created, location: @neighbors_invitation }
      else
        format.html { render :new }
        format.json { render json: @neighbors_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighbors_invitations/1
  # PATCH/PUT /neighbors_invitations/1.json
  def update
    respond_to do |format|
      if @neighbors_invitation.update(neighbors_invitation_params)
        format.html { redirect_to @neighbors_invitation, notice: 'Neighbors invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighbors_invitation }
      else
        format.html { render :edit }
        format.json { render json: @neighbors_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighbors_invitations/1
  # DELETE /neighbors_invitations/1.json
  def destroy
    @neighbors_invitation.destroy
    respond_to do |format|
      format.html { redirect_to neighbors_invitations_url, notice: 'Neighbors invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighbors_invitation
      @neighbors_invitation = NeighborsInvitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighbors_invitation_params
      params.require(:neighbors_invitation).permit(:family_id, :neighbor_id, :status, :user_id, :initial_text, :respond_by_id, :response_text, :respond_at)
    end
end

app/helpers/neighbors_invitations_helper.rb
module NeighborsInvitationsHelper
end

app/views/neighbors_invitations/_form.html.erb
<%= form_for @neighbors_invitation, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :family_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :family_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :neighbor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :neighbor_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :initial_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :initial_text, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :respond_by_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :respond_by_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :response_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :response_text, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :respond_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :respond_at, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                neighbors_invitations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/neighbors_invitations/edit.html.erb
<%- model_class = NeighborsInvitation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighbors_invitations/index.html.erb
<%- model_class = NeighborsInvitation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:family_id) %></th>
      <th><%= model_class.human_attribute_name(:neighbor_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:initial_text) %></th>
      <th><%= model_class.human_attribute_name(:respond_by_id) %></th>
      <th><%= model_class.human_attribute_name(:response_text) %></th>
      <th><%= model_class.human_attribute_name(:respond_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @neighbors_invitations.each do |neighbors_invitation| %>
      <tr>
        <td><%= link_to neighbors_invitation.id, neighbors_invitation_path(neighbors_invitation) %></td>
        <td><%= neighbors_invitation.family %></td>
        <td><%= neighbors_invitation.invited_family %></td>
        <td><%= neighbors_invitation.status %></td>
        <td><%= neighbors_invitation.user.supervisor %></td>
        <td><%= neighbors_invitation.invitation_text %></td>
        <td><%= neighbors_invitation.respond_by.try(:name) %></td>
        <td><%= neighbors_invitation.response_text %></td>
        <td><%= neighbors_invitation.respond_at %></td>
        <td><%=l_with_time_zone neighbors_invitation.invited_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_neighbors_invitation_path(neighbors_invitation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      neighbors_invitation_path(neighbors_invitation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_neighbors_invitation_path,
            :class => 'btn btn-primary' %>

app/views/neighbors_invitations/new.html.erb
<%- model_class = NeighborsInvitation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighbors_invitations/show.html.erb
<%- model_class = NeighborsInvitation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:family_id) %>:</strong></dt>
  <dd><%= @neighbors_invitation.family_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighbor_id) %>:</strong></dt>
  <dd><%= @neighbors_invitation.neighbor_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @neighbors_invitation.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @neighbors_invitation.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:initial_text) %>:</strong></dt>
  <dd><%= @neighbors_invitation.initial_text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:respond_by_id) %>:</strong></dt>
  <dd><%= @neighbors_invitation.respond_by_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:response_text) %>:</strong></dt>
  <dd><%= @neighbors_invitation.response_text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:respond_at) %>:</strong></dt>
  <dd><%= @neighbors_invitation.respond_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              neighbors_invitations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_neighbors_invitation_path(@neighbors_invitation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              neighbors_invitation_path(@neighbors_invitation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>