config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/models/neighbors_families_link.rb
class NeighborsFamiliesLink < ActiveRecord::Base
  belongs_to :family
  belongs_to :neighbor_family, class_name: 'Family'
  belongs_to :neighbors_invitation
end

app/controllers/neighbors_families_links_controller.rb
class NeighborsFamiliesLinksController < ApplicationController

  # GET /neighbors_families_links
  # GET /neighbors_families_links.json
  def index
    @neighbors_families_links = NeighborsFamiliesLink.all.paginate(:page => params[:page],:per_page => 10)
  end
end

app/helpers/neighbors_families_links_helper.rb
module NeighborsFamiliesLinksHelper
end

app/views/neighbors_families_links/_form.html.erb
<%= form_for @neighbors_families_link, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :family_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :family_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :neighbor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :neighbor_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :neighbors_invitation_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :neighbors_invitation_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                neighbors_families_links_path, :class => 'btn' %>
  </div>
<% end %>

app/views/neighbors_families_links/edit.html.erb
<%- model_class = NeighborsFamiliesLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighbors_families_links/index.html.erb
<%- model_class = NeighborsFamiliesLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:family_id) %></th>
      <th><%= model_class.human_attribute_name(:neighbor_id) %></th>
      <th><%= model_class.human_attribute_name(:neighbors_invitation_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @neighbors_families_links.each do |neighbors_families_link| %>
      <tr>
        <td><%= link_to neighbors_families_link.id, neighbors_families_link_path(neighbors_families_link) %></td>
        <td><%= neighbors_families_link.family_id %></td>
        <td><%= neighbors_families_link.neighbor_id %></td>
        <td><%= neighbors_families_link.neighbors_invitation_id %></td>
        <td><%=l_with_time_zone neighbors_families_link.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_neighbors_families_link_path(neighbors_families_link), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      neighbors_families_link_path(neighbors_families_link),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_neighbors_families_link_path,
            :class => 'btn btn-primary' %>

app/views/neighbors_families_links/new.html.erb
<%- model_class = NeighborsFamiliesLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighbors_families_links/show.html.erb
<%- model_class = NeighborsFamiliesLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:family_id) %>:</strong></dt>
  <dd><%= @neighbors_families_link.family_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighbor_id) %>:</strong></dt>
  <dd><%= @neighbors_families_link.neighbor_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighbors_invitation_id) %>:</strong></dt>
  <dd><%= @neighbors_families_link.neighbors_invitation_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              neighbors_families_links_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_neighbors_families_link_path(@neighbors_families_link), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              neighbors_families_link_path(@neighbors_families_link),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>